version: '3.7'

services:
  web:
    build:
      context: './app'
      dockerfile: Dockerfile.prod
    command: gunicorn ssh_secret.wsgi:application --bind 0.0.0.0:8000
    ports:
      - 8000:8000
    env_file:
      - ./.env.prod
    depends_on:
      - db
  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.prod.db
  ssh:
    build:
      context: './ssh'
      args:
        SSH_USER: ${SSH_USER}
        SSH_PASS: ${SSH_PASS}
    ports:
      - "2222:22"

volumes:
  postgres_data: