version: '3.7'

services:
    web:
        build: './app'
        command: python manage.py runserver 0.0.0.0:8000
        volumes:
        - ./app/:/usr/src/app/
        ports:
        - 8000:8000
        env_file:
          - ./.env.dev
    db:
        image: postgres:12.0-alpine
        volumes:
        - postgres_data:/var/lib/postgresql/data/
        environment:
            - POSTGRES_USER=admin
            - POSTGRES_PASSWORD=P@ssw0rd
            - POSTGRES_DB=ssh_secret_dev
    ssh:
        build:
            context: './ssh'
            args:
                SSH_USER: ${SSH_USER}
                SSH_PASS: ${SSH_PASS}
        ports:
            - "2222:22"
        env_file:
            - ./.env.dev

volumes:
  postgres_data: